theme: 'hugo-theme-readable'
title: 'U Tulsa ARC'

languages:
  en:
    languageName: English
    menu:
      main:
      - name: Blog
        url: /posts
        weight: 10
      - name: Home
        url: /
        weight: 1

frontmatter:
  lastmod:
  - lastmod
  - date
  - publishDate
